name: PR Branch Labeler

on: pull_request

permissions: write-all

jobs:
  label_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Label PRs
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          config-pathname: .github/pr-branch-labeler.yml

